//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HovisMillingPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Hovis_Milling_User_Plant_Authorisation
    {
        public int UserPlantRecid { get; set; }
        public Nullable<int> PlantRecid { get; set; }
        public string UserName { get; set; }
    }
}
