//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HovisMillingPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Milling_Bacs_Master_Data
    {
        public long MasterRecid { get; set; }
        public string BacsID { get; set; }
        public string MasterBankSortCode { get; set; }
        public string MasterBankAccountNo { get; set; }
        public string MasterBankAccountName { get; set; }
        public string CreatedBy { get; set; }
        public string LastChangedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastChangedDate { get; set; }
        public string StreetName { get; set; }
        public string PostCode { get; set; }
        public string TownName { get; set; }
        public string CntrySubDiv { get; set; }
        public string Country { get; set; }
        public string Currency { get; set; }
        public string BIC { get; set; }
        public string IBAN { get; set; }
        public string MMBID { get; set; }
        public string TaxId { get; set; }
        public string InstrId { get; set; }
    }
}
