//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HovisMillingPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Milling_Bacs_Header
    {
        public long HeaderRecid { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> StageFlag { get; set; }
        public Nullable<int> DDFrequency { get; set; }
        public string BacsID { get; set; }
        public string MasterBankSortCode { get; set; }
        public string MasterBankAccountNo { get; set; }
        public string MasterBankAccountName { get; set; }
        public string CreatedBy { get; set; }
        public string LastChangedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastChangedDate { get; set; }
        public string SentBy { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string AuthorisedBy { get; set; }
        public Nullable<System.DateTime> AuthorisedDate { get; set; }
        public Nullable<int> RejectedFlag { get; set; }
    }
}
