//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HovisMillingPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Milling_UMQC_Products_Master
    {
        public long ProductMasterRecid { get; set; }
        public string RecipeCode { get; set; }
        public string RecipeDesc { get; set; }
        public string ItemCode { get; set; }
        public string ItemDesc { get; set; }
        public string RecipeCreatedBy { get; set; }
        public Nullable<System.DateTime> RecipeCreatedDate { get; set; }
        public string RecipeLastChangedBy { get; set; }
        public Nullable<System.DateTime> RecipeLastChangedDate { get; set; }
        public Nullable<int> RecipeActiveFlag { get; set; }
    }
}
