//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HovisMillingPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Milling_Bacs_Customers
    {
        public long CustomerRecid { get; set; }
        public string CustomerNo { get; set; }
        public string SortingCode { get; set; }
        public string BankAccountNo { get; set; }
        public string BankAccountName { get; set; }
        public Nullable<int> Status { get; set; }
        public string BankMandateDate { get; set; }
        public Nullable<int> DDFrequency { get; set; }
        public Nullable<int> NewBankMandate { get; set; }
        public Nullable<int> FirstClaim { get; set; }
        public Nullable<int> SecondClaim { get; set; }
        public string CreatedBy { get; set; }
        public string LastChangedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastChangedDate { get; set; }
    }
}
